<?php
namespace unclead\multipleinput\tests\unit\data;


use yii\db\ActiveRecord;

class TestActiveRecord extends ActiveRecord
{
    /**
     * @var string
     */
    public $email;
    public $testRelation = null;

    public function rules()
    {
        return [
            ['email', 'safe']
        ];
    }

    public function attributeLabels()
    {
        return [
            'email' => 'Email',
        ];
    }

    public function getTestHasOneRelation() {}

    public function attributes()
    {
        return ['testRelation']; // TODO: Change the autogenerated stub
    }

    public function getAttribute($name)
    {
        if ($name === 'testRelation') {
            return $this->testRelation;
        }

        return parent::getAttribute($name);
    }

    public function getTestRelation() {
        return $this->hasOne(TestActiveRecordRelated::class, []);
    }
}