<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 12/3/19
 * Time: 1:14 PM
 */

namespace unclead\multipleinput\tests\unit\data;


use yii\db\ActiveRecord;

class TestActiveRecord extends ActiveRecord
{
    /**
     * @var string
     */
    public $email;

    public function rules()
    {
        return [
            ['email', 'safe']
        ];
    }

    public function attributeLabels()
    {
        return [
            'email' => 'Email',
        ];
    }

    public function getTestHasOneRelation() {}

    public function attributes()
    {
        return ['databaseAttribute']; // TODO: Change the autogenerated stub
    }

    protected $_databaseAttribute = null;
    public function setDatabaseAttribute($value) {
        $this->_databaseAttribute = $value;
    }

    public function getAttribute($name)
    {
        if ($name === 'databaseAttribute') {
            return $this->_databaseAttribute;
        }

        return parent::getAttribute($name);
    }
}